version: '3.4'
services:
  react-app:
    network_mode: 'host'
    image: raymondpulver/kool-scanner
    build:
      dockerfile: Dockerfile
      context: ./
  nginx:
    network_mode: 'host'
    user: 0:0
    image: nginx
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
