version: '3.4'
services:
  scanner:
    network_mode: 'host'
    ports:
      - "443:443"
      - "80:80"
    user: 0:0
    image: raymondpulver/kool-scanner
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - /root/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
